const APP_URL = process.env.APP_URL || 'http://localhost:8080'

describe('Pokemon page', () => {
  it('should render correctly home page', () => {
    cy.visit(APP_URL)
  })
  it('should render input field', () => {
    cy.visit(APP_URL)
    cy.get('input')
    .should('be.visible')
    .should('have.attr', 'placeholder')
  })
  it('should render content', () => {
    cy.visit(APP_URL)
    cy.wait(400)
    cy.get('#container > :nth-child(1) img')
    .should('have.attr', 'alt', 'bulbasaur')
    cy.get('#container > :nth-child(1) p')
    .contains('bulbasaur')
    cy.get(':nth-child(1) > .infos > :nth-child(2)')
    .contains('#1')
  })
  it('should render correctly results for search', () => {
    cy.visit(APP_URL)
    cy.get('input')
    .type('Char')
    cy.get('#container > :nth-child(1) img')
    .should('have.attr', 'alt', 'charmander')
    .should('not.have.attr', 'alt', 'bulbasaur')
    cy.get(':nth-child(1) > .infos > :nth-child(2)')
    .contains('#4')
    cy.get(':nth-child(1) > .infos > :nth-child(2)')
    .should('not.contain', '#1')
    cy.get('#container')
    .filter(':contains("charmander")')
    .filter(':contains("charmeleon")')
    .filter(':contains("charizard")')
  })
  it('should render correctly unique result for search', () => {
    cy.visit(APP_URL)
    cy.get('input')
    .type('charizard')
    cy.get('#container > :nth-child(1) p')
    .contains('charizard')
    .filter(':contains("charizard")')
    cy.get('#container > :nth-child(2)')
    .should('not.exist')
    cy.get('#container > :nth-child(3)')
    .should('not.exist')
  })
  it('should render a not found message for results empty', () => {
    cy.visit(APP_URL)
    cy.get('input')
    .type('xxxx')
    cy.get('p')
    .contains('Ops...Nenhum Pokémon encontrado.')
    cy.get('#container')
    .should('not.exist')
  })
})
